# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "spoa"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "spoa":
      description: "SIMD partial order alignment tool/library."
      homepage: "https://github.com/rvaser/spoa/blob/4.1.5/README.md"
      documentation: "https://github.com/rvaser/spoa/blob/4.1.5/README.md"
      tool_dev_url: "https://github.com/rvaser/spoa"
      doi: ""
      licence: ["MIT"]
      identifier: biotools:spoa

input:
  # TODO nf-core: Update the information obtained from bio.tools and make sure that it is correct
  - - meta:
        type: map
        description: Groovy Map containing sample information. e.g. `[
          id:'sample1' ]`
    - tool_name_(fasta):
        type: file
        description: tool_name_(fasta) file
        pattern: "*.{zip}"
        ontologies:
          - edam: http://edamontology.org/data_1193 # Tool name (FASTA)
          - edam: http://edamontology.org/format_3987 # ZIP format
output:
  # TODO nf-core: Update the information obtained from bio.tools and make sure that it is correct
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@snunzi"
maintainers:
  - "@snunzi"
