# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "vsearch_orient"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "vsearch":
      description: "A versatile open source tool for metagenomics (USEARCH alternative)."
      homepage: "https://torognes.github.io/vsearch"
      documentation: "https://torognes.github.io/vsearch"
      tool_dev_url: "https://github.com/torognes/vsearch"
      doi: ""
      licence: ["GPL v3-or-later OR BSD-2-clause"]
      identifier: biotools:vsearch

input:
  # TODO nf-core: Update the information obtained from bio.tools and make sure that it is correct
  - - meta:
        type: map
        description: Groovy Map containing sample information. e.g. `[
          id:'sample1' ]`
    - nucleic_acid_sequence:
        type: file
        description: nucleic_acid_sequence file
        pattern: "*.{}"
        ontologies:
          - edam: http://edamontology.org/data_2977 # Nucleic acid sequence
output:
  # TODO nf-core: Update the information obtained from bio.tools and make sure that it is correct
  sequence_similarity_score:
    - - meta:
          type: map
          description: Groovy Map containing sample information. e.g. `[
            id:'sample1' ]`
      - "*.{}":
          type: file
          description: sequence_similarity_score file
          pattern: "*.{}"
          ontologies:
            - edam: http://edamontology.org/data_0865 # Sequence similarity score
  sequence_alignment:
    - - meta:
          type: map
          description: Groovy Map containing sample information. e.g. `[
            id:'sample1' ]`
      - "*.{}":
          type: file
          description: sequence_alignment file
          pattern: "*.{}"
          ontologies:
            - edam: http://edamontology.org/data_0863 # Sequence alignment
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@snunzi"
maintainers:
  - "@snunzi"
